name: Create Document issue for Merge Request

# Run this action when we merge into master
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  # Create an issue on the documentation repository to document whatever was just pulled in.
  create-doc-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check for 'needs doc' label
        outputs:
          needs-doc:
            description: 'boolean as to whether the PR needs a doc ticket'
        run: |
          IFS='
          '
          PR_NUM=${{ github.event.pull_request.number }}
          LABELS=$(curl "https://api.github.com/repos/johrstrom/ondemand/issues/$PR_NUM" | jq '.labels[].name')

          # make labels a bash array
          declare -a LABELS=($LABELS)
          echo "all labels are [${LABELS[@]}]"

          echo "::set-output name=needs_doc::false"
          for LABEL in ${LABELS[@]}; do
            if [[ "$LABEL" == '"needs doc"' ]]; then
              echo 'found $LABEL label'
              echo "::set-output name=needs-doc::true"
            fi
          done
          
      - name: Create an issue on the documentation repository
        if: steps.create-doc-issue.outputs.needs-doc
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          TITLE="Create Docs for OOD PR #$PR_NUM"
          BODY="{
             \"title\": \"$TITLE\",
             \"body\": \"Create documentation for https://github.com/johrstrom/ondemand/pulls/$PR_NUM\"
          }"

          curl --silent --output /dev/null --request POST \
          --url https://api.github.com/repos/johrstrom/other-test-actions/issues \
          --header 'Authorization: token ${{ secrets.MY_ISSUE_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "$BODY"
