name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  update-dependencies:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["2.7.1"]
        bundler: ["2.1.4"]
    runs-on: ${{ matrix.os }}
    name: Update Dependencies

    steps:
      - name: Checkout ${{ github.sha	}}
        uses: actions/checkout@v2

      - name: Setup Ruby ${{ matrix.ruby }} using Bundler ${{ matrix.bundler }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('apps/*/Gemfile.lock') }}

      - name: Setup Bundler
        run: |
          bundle config path ~/vendor/bundle


      - name: Setup git
        run: |
          git config --global user.email johrstrom@hotmail.com
          git config --global user.name "Jeff Ohrstrom"

      - name: Run Rake Update
        run: rake update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_ISSUE_TOKEN }}
          commit-message: update dependencies
          committer: Jeff Ohrstrom <johrstrom@hotmail.com>
          author: johrstrom <johrstrom@hotmail.com>
          branch: oscwiag-dep-updates
          delete-branch: true
          title: 'Update Dependencies'
          body: |
            Update dependencies generated from `rake update`